// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVg3Do4dvWHhmlL7kZJu6YwF1LmDVYHug',
    appId: '1:530870806053:web:3cd09853cfbd54503201cc',
    messagingSenderId: '530870806053',
    projectId: 'drikaprof',
    authDomain: 'drikaprof.firebaseapp.com',
    storageBucket: 'drikaprof.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLwiXfLBffLZM14_TplHxbG06n2-ZOiCA',
    appId: '1:530870806053:android:595e7fc2ba65fbc33201cc',
    messagingSenderId: '530870806053',
    projectId: 'drikaprof',
    storageBucket: 'drikaprof.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCykrhO0mQ20k3foECtxduQQY8yS-S6wGE',
    appId: '1:530870806053:ios:6fb6a852cea83a313201cc',
    messagingSenderId: '530870806053',
    projectId: 'drikaprof',
    storageBucket: 'drikaprof.appspot.com',
    iosBundleId: 'com.example.drikaprof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCykrhO0mQ20k3foECtxduQQY8yS-S6wGE',
    appId: '1:530870806053:ios:f90eed1912d33ca83201cc',
    messagingSenderId: '530870806053',
    projectId: 'drikaprof',
    storageBucket: 'drikaprof.appspot.com',
    iosBundleId: 'com.example.drikaprof.RunnerTests',
  );
}
